# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'pry'
gem 'mongoid'
gem 'twitter'
gem 'rake'
gem 'whatlanguage'
gem 'minitest'
